name: Build check - ubuntu-latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm
        vcpkg install libvpx libyuv opus aom
        sudo apt-get install -y --fix-missing libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
