name: Build check - ubuntu-latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: vcpkg install libvpx libyuv opus aom
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
